### PR TITLE
Update to Metalsmith 0.11.0

### PR DESCRIPTION
**Pull request by alexwhitman**

### CODE REVIEW

**Comment by doingweb** [comment]
I'd like to set up Travis to make sure this (and future PRs) build okay. Though, if you have an immediate need, I can take your word that it won't break anything and merge now.

Of course, if you are familiar with Travis and feel like pushing in a working config, that would be even better. :)

**Comment by alexwhitman** [comment]
I rebased this onto master so that it's tested with Travis:
- Failed on 0.8 because of `setImmediate`
- Failed on 0.10, not sure why without looking into it
- Passed on 0.11

**Comment by doingweb** [comment]
Ah yes, the `has no method 'equals'` error is from bingomanatee/node-dir-diff#2, where [node-dir-diff](https://github.com/bingomanatee/node-dir-diff) is using [node-filecompare](https://github.com/rook2pawn/node-filecompare) v0.0.2, which has an [unversioned dependency](https://github.com/rook2pawn/node-filecompare/blob/cfebd8bcb26bcea0ef12bab70cac13ebdae2d534/package.json#L13) on [node-buffertools](https://github.com/bnoordhuis/node-buffertools), which introduced a breaking change at bnoordhuis/node-buffertools@20b192152d398b2d5b301f00d1e5daa22f6f2e23.

node-dir-diff has to catch up with node-filecompare to make that go away. Or, if you know of a better method for comparing directories in the context of a nodeunit test, I'd be open to doing these tests a bit differently.

I feel like it would be reasonable to expect a more recent version in the environments where this is likely to be used, so I'm comfortable cutting v0.8. I googled around for some stats on version usage share and came up empty, so if you have some data that makes the opposite case, please share.

Since we have a clean pass, I'll merge and deal with the red build later. Thanks!

**Comment by alexwhitman** [comment]
Thanks for merging.  Any chance of publishing a new version to NPM or do you want to fix the tests first?

**Comment by doingweb** [comment]
Of course! I always forget that part, sorry. Try now. :)

**Comment by alexwhitman** [comment]
Works fine, thanks again.

**Pull request merged**
