### PR TITLE
Update metalsmith dependency to ^1.0.0.

### PR DESCRIPTION
**Pull request by mwbrooks**
I have a few metalsmith dependencies that require a `1.x.x` release of metalsmith, so I'd appreciate having the metalsmith dependency bumped!

I've chosen the caret range selector to match the consistency of the other npm dependencies.

Cheers,
Michael

### CODE REVIEW

**Comment by doingweb** [comment]
Any breaking changes in 1.0? Anything that would affect [how Metalsmith is used](https://github.com/doingweb/grunt-metalsmith/blob/2449d9ae1800ca5f3d92c1e39a3ac60a66fb2921/tasks/metalsmith.js#L23), or how people need to set up their Grunt config?  Thanks!

**Comment by mwbrooks** [comment]
Hey @doingweb,

Honestly, I only started using metalsmith after the 1.0.0 release, so I'm not sure what has changed. My problem is that a few of the metalsmith middleware libraries require the 1.0.0 interface. Since those break, I imagine there are some other interfaces that may be broken.

I'm seeing that your Travis CI tests are failing. How about I start by ensuring that your tests pass and review what `metalsmith.json` configurations changed between the versions.

**Comment by doingweb** [comment]
Ah yes, about the tests, feel free to remove [the node v0.10 target](https://github.com/doingweb/grunt-metalsmith/blob/master/.travis.yml#L4) if you come up against the "has no method 'equals'" error last seen in [build 6.2](https://travis-ci.org/doingweb/grunt-metalsmith/jobs/35675722). See #1 for more details.

Thanks again, and I look forward to your updates. :)

**Comment by alexwhitman** [comment]
Just came here to suggest doing an update for the 1.x version. :+1:

**Comment by doingweb** [comment]
Forget what I said about removing the v0.10 target; I'm looking into this now, and have realized that v0.10 is actually [the current version](http://nodejs.org/download/).

**Comment by doingweb** [comment]
I've created [a new branch](https://github.com/doingweb/grunt-metalsmith/tree/updating-metalsmith) for the work of updating the Metalsmith dependency and working through any issues that come up. Please feel free to come join me on that and send some PRs my way. :)

**Comment by doingweb** [comment]
[Merged](https://github.com/doingweb/grunt-metalsmith/releases/tag/v1.0.0) and [published](https://www.npmjs.org/package/grunt-metalsmith)! And [the build even passes](https://travis-ci.org/doingweb/grunt-metalsmith/builds/41316936)!

**Comment by mwbrooks** [comment]
yaya!

**Pull request closed without merging**
